# supabase/config.toml — functions schedules

[functions.whatsapp-broadcast]
verify_jwt = false
schedule = "0 9 * * *"          # every day at 09:00

[functions.reminders]
verify_jwt = false
schedule = "0 * * * *"          # hourly

# Kept from branch: codex/add-whatsapp-opt-in-preferences-panel
[functions.whatsapp-tasks]
verify_jwt = true                # invoked by app/webhook; no schedule

# Kept from main branch
[functions.daily-plan-reminders]
verify_jwt = false
schedule = "0 7 * * *"          # every day at 07:00
