// lib/analytics/events.ts

export type AnalyticsEventName =
  | 'signup'
  | 'onboarding_completed'
  | 'onboarding_start'
  | 'onboarding_step_complete'
  | 'onboarding_done'
  | 'profile_save'
  | 'studyplan_create'
  | 'studyplan_update'
  | 'saved_view'
  | 'saved_remove'
  | 'mock_started'
  | 'mock_completed'
  | 'ai_feedback_viewed'
  | 'paywall_view'
  | 'subscribe_clicked'
  | 'plan_purchased'
  | 'referral_link_created'
  | 'referral_redeemed'
  | 'partner_code_applied'
  | 'predictor_completed'
  | 'vocab_review_start'
  | 'vocab_review_finish'
  | 'grade_submitted'
  | 'speaking_attempt'
  | 'writing_eval'
  | 'badge_unlocked'
  | 'challenge_started'
  | 'challenge_completed'
  | 'challenge_joined'
  | 'certificate_shared'
  | 'teacher_review_started'
  | 'teacher_review_completed'
  | 'teacher_review_scored'
  | 'writing_essay_scored'
  | 'writing.score.v2'
  | 'writing.view.band9'
  | 'writing.view.highlights'
  | 'analytics.progress.view'
  | 'xp.award.writing'
  | 'leaderboard.view.writing'
  | 'vocab_word_viewed'
  | 'vocab_meaning_submitted'
  | 'vocab_sentence_submitted'
  | 'vocab_synonyms_submitted'
  | 'vocab_reward_shown'
  | 'vocab_share_clicked'
  | 'coach.writing.session'
  | 'coach.writing.reply'
  | 'saved_view'
  | 'saved_remove'
  | 'reading.highlight.add'
  | 'reading.note.add'
  | 'reading.flag.toggle'
  | 'reading.nav.filter';

export type AnalyticsProps = Record<
  string,
  string | number | boolean | null | undefined
>;
