-- Create login_events table to track login history
create table if not exists login_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  ip_address text,
  user_agent text
);

alter table login_events enable row level security;

-- Allow users to view their own events
create policy "Users view own login events" on login_events
  for select using (auth.uid() = user_id);

-- Service role inserts events
create policy "Allow insert" on login_events
  for insert with check (true);
