-- Create exam_events table to log anti-cheat events
create table if not exists exam_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null,
  user_id uuid references auth.users(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now()
);

alter table exam_events enable row level security;

-- Users can view their own events
create policy "Users view own exam events" on exam_events
  for select using (auth.uid() = user_id);

-- Users insert their own events
create policy "Users insert exam events" on exam_events
  for insert with check (auth.uid() = user_id);
