-- Auto-generated by tools/generate_word_bank.py
-- Inserts/updates word drill packs with collocations, IELTS-tagged examples, and audio references.

insert into public.word_packs (word_id, slug, register, audio_ref, collocations, examples)
select id,
       'climate-action',
       'formal',
       'https://cdn.gramorx.com/audio/climate.mp3',
       ARRAY['climate change mitigation', 'climate resilience strategy', 'climate action plan'],
       '[{"text":"In IELTS Writing Task 2, evaluate whether a national climate action plan balances economic growth with environmental protection.","tags":["ielts-writing-task-2"]},{"text":"For IELTS Speaking Part 3, discuss how climate resilience strategies help coastal communities prepare for storms.","tags":["ielts-speaking-part-3"]}]'::jsonb
from public.words
where lower(word) = 'climate'
on conflict (word_id, slug) do update
set register = excluded.register,
    audio_ref = excluded.audio_ref,
    collocations = excluded.collocations,
    examples = excluded.examples,
    updated_at = now();

insert into public.word_packs (word_id, slug, register, audio_ref, collocations, examples)
select id,
       'urban-development',
       'neutral',
       null,
       ARRAY['urban regeneration project', 'urban transport network', 'urban sprawl control'],
       '[{"text":"Describe an urban regeneration project in IELTS Speaking Part 2 and highlight the public transport improvements it delivered.","tags":["ielts-speaking-part-2"]},{"text":"In IELTS Writing Task 1, compare two urban transport networks using precise data language and cohesive comparisons.","tags":["ielts-writing-task-1"]}]'::jsonb
from public.words
where lower(word) = 'urban'
on conflict (word_id, slug) do update
set register = excluded.register,
    audio_ref = excluded.audio_ref,
    collocations = excluded.collocations,
    examples = excluded.examples,
    updated_at = now();

insert into public.word_packs (word_id, slug, register, audio_ref, collocations, examples)
select id,
       'housing-strategies',
       'formal',
       'https://cdn.gramorx.com/audio/housing.mp3',
       ARRAY['affordable housing scheme', 'housing shortage', 'public housing investment'],
       '[{"text":"Outline an affordable housing scheme in IELTS Writing Task 2, noting benefits for urban residents.","tags":["ielts-writing-task-2"]},{"text":"Discuss how public housing investment affects community wellbeing in IELTS Speaking Part 3.","tags":["ielts-speaking-part-3"]}]'::jsonb
from public.words
where lower(word) = 'housing'
on conflict (word_id, slug) do update
set register = excluded.register,
    audio_ref = excluded.audio_ref,
    collocations = excluded.collocations,
    examples = excluded.examples,
    updated_at = now();
