import json
from pathlib import Path

TESTS = [
    {
        "num": "002",
        "title": "IELTS Listening Full Mock Exam 002",
        "transcript": "This paper mirrors the IELTS format with a student housing enquiry, an innovation tour briefing, a group mobility project meeting, and a lecture on smart transit grids.",
        "section1": {
            "title": "Section 1 — Student Housing Inquiry",
            "venue": "Brookside Residence Lounge",
            "venueOptions": ["Brookside Residence Lounge", "Harbor View Hall", "Library Seminar Suite", "Crescent Pavilion"],
            "date": "14th October",
            "startTime": "7:00 pm",
            "guests": "120",
            "catering": "Mediterranean buffet",
            "cateringOptions": ["Mediterranean buffet", "Vegan canapés", "Street food vans", "Formal three-course dinner"],
            "deposit": "250 pounds",
            "equipment": "wireless microphones",
            "keyCollector": "Sophie",
            "parking": "Underground car park B",
            "parkingOptions": ["Underground car park B", "East surface lot", "Visitor bays on King Street", "Overflow field"],
            "layout": "banquet style",
        },
        "section2": {
            "title": "Section 2 — Campus Innovation Tour Briefing",
            "role": "innovation tour coordinator",
            "roleOptions": ["innovation tour coordinator", "student ambassador", "operations supervisor", "guest lecturer"],
            "topic": "orientation briefing for the new makerspace",
            "duration": "25 minutes",
            "meetingPoint": "Old Clock Tower plaza",
            "firstStop": "Prototyping Lab",
            "firstStopOptions": ["Prototyping Lab", "Media Studio", "Roof Garden", "Fabrication Wing"],
            "studioLabel": "Room F",
            "wifi": "Makers-2025",
            "qaDay": "Friday",
            "bringItem": "closed-toe shoes",
            "bringOptions": ["closed-toe shoes", "formal suits", "printed tickets", "sports equipment"],
            "emergencyContact": "0207 555 1940",
        },
        "section3": {
            "title": "Section 3 — Group Discussion on Mobility Study",
            "topic": "urban micro-mobility study",
            "topicOptions": ["urban micro-mobility study", "campus dining review", "library refurbishment", "sports participation survey"],
            "lead": "Amelia",
            "deadline": "18 November",
            "meeting": "twice a week",
            "method": "mixed-method interviews",
            "methodOptions": ["mixed-method interviews", "online polls only", "archival research", "laboratory experiments"],
            "software": "InsightLab",
            "budget": "£450",
            "lecturer": "Dr. Chen",
            "challenge": "recruiting enough night-shift workers",
            "challengeOptions": ["recruiting enough night-shift workers", "booking the conference hall", "editing the audio guides", "transporting lab samples"],
            "presentationLength": "12 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Smart Transit Grids",
            "focus": "integrated smart transit grids",
            "focusOptions": ["integrated smart transit grids", "heritage tourism marketing", "marine biology fieldwork", "culinary entrepreneurship"],
            "stat": "42 percent",
            "term": "adaptive routing corridors",
            "case": "Rotterdam",
            "driver": "citywide sensor data sharing",
            "driverOptions": ["citywide sensor data sharing", "private sponsorship deals", "seasonal tourism demand", "student volunteer hours"],
            "team": "Atlas Institute",
            "reading": "Smart Mobility 2035 report",
            "pilotYear": "2021",
            "challenge": "aligning legacy ticketing systems",
            "challengeOptions": ["aligning legacy ticketing systems", "training volunteer docents", "maintaining coral nurseries", "protecting recipe IP"],
            "takeaway": "design for adaptability",
        },
    },
    {
        "num": "003",
        "title": "IELTS Listening Full Mock Exam 003",
        "transcript": "Candidates will hear a conference catering enquiry, a museum audio-guide briefing, a retrofit planning seminar, and an academic lecture on circular design.",
        "section1": {
            "title": "Section 1 — Conference Catering Request",
            "venue": "Riverside Conference Suite",
            "venueOptions": ["Riverside Conference Suite", "Hilltop Conservatory", "West Pier Atrium", "Oakwood Ballroom"],
            "date": "3rd December",
            "startTime": "9:30 am",
            "guests": "180",
            "catering": "Seasonal brunch buffet",
            "cateringOptions": ["Seasonal brunch buffet", "Gourmet sandwich platters", "Tapas evening", "Outdoor barbecue"],
            "deposit": "320 pounds",
            "equipment": "dual projectors",
            "keyCollector": "Liam",
            "parking": "Multi-storey car park C",
            "parkingOptions": ["Multi-storey car park C", "Riverside lay-bys", "Staff courtyard", "Coach bays by Gate 2"],
            "layout": "theatre seating",
        },
        "section2": {
            "title": "Section 2 — Museum Audio Guide Briefing",
            "role": "museum education officer",
            "roleOptions": ["museum education officer", "gallery assistant", "security supervisor", "volunteer coordinator"],
            "topic": "updated audio guide launch",
            "duration": "18 minutes",
            "meetingPoint": "Sculpture Garden entrance",
            "firstStop": "Restored Gallery Two",
            "firstStopOptions": ["Restored Gallery Two", "Temporary Exhibit Hall", "Archive Reading Room", "Cafe mezzanine"],
            "studioLabel": "Stand 4",
            "wifi": "GalleryNet-88",
            "qaDay": "Saturday",
            "bringItem": "personal headphones",
            "bringOptions": ["personal headphones", "formal dress shoes", "printed brochures", "tripods"],
            "emergencyContact": "0114 890 2231",
        },
        "section3": {
            "title": "Section 3 — Seminar on Renewable Dorms",
            "topic": "residential energy retrofit project",
            "topicOptions": ["residential energy retrofit project", "student wellbeing survey", "campus theatre review", "athletics sponsorship plan"],
            "lead": "Noor",
            "deadline": "27 October",
            "meeting": "every Monday evening",
            "method": "energy meter logging",
            "methodOptions": ["energy meter logging", "paper questionnaires", "focus groups only", "lab simulations"],
            "software": "GridTrack",
            "budget": "£520",
            "lecturer": "Professor Ellis",
            "challenge": "coordinating access to dorm rooms",
            "challengeOptions": ["coordinating access to dorm rooms", "booking translators", "scheduling keynote speakers", "ordering lab reagents"],
            "presentationLength": "15 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Circular Design",
            "focus": "circular design for consumer tech",
            "focusOptions": ["circular design for consumer tech", "agricultural irrigation", "polar climate change", "medieval literature"],
            "stat": "68 percent",
            "term": "material passport",
            "case": "Helsinki",
            "driver": "regenerative manufacturing incentives",
            "driverOptions": ["regenerative manufacturing incentives", "fashion trends", "record tourism revenue", "celebrity endorsements"],
            "team": "Nova Research Lab",
            "reading": "Circular Systems Digest",
            "pilotYear": "2019",
            "challenge": "tracing supplier compliance",
            "challengeOptions": ["tracing supplier compliance", "hiring seasonal guides", "protecting coral reefs", "managing rehearsal schedules"],
            "takeaway": "close loops early",
        },
    },
    {
        "num": "004",
        "title": "IELTS Listening Full Mock Exam 004",
        "transcript": "Expect a community sports day booking call, an outdoor festival layout briefing, a planning debate on a community garden, and a lecture on heat island mitigation.",
        "section1": {
            "title": "Section 1 — Community Sports Day Booking",
            "venue": "Lakeside Activity Center",
            "venueOptions": ["Lakeside Activity Center", "Harbor Loft", "City Library Hall", "Greenfield Barn"],
            "date": "22nd May",
            "startTime": "10:00 am",
            "guests": "95",
            "catering": "Healthy picnic packs",
            "cateringOptions": ["Healthy picnic packs", "Gala dinner service", "Food truck lineup", "Dessert tasting bar"],
            "deposit": "180 pounds",
            "equipment": "portable sound system",
            "keyCollector": "Jordan",
            "parking": "North overflow lot",
            "parkingOptions": ["North overflow lot", "Riverbank street parking", "Staff garage", "Community center basement"],
            "layout": "cluster tables",
        },
        "section2": {
            "title": "Section 2 — Outdoor Festival Briefing",
            "role": "events safety manager",
            "roleOptions": ["events safety manager", "stage producer", "volunteer marshal", "marketing officer"],
            "topic": "layout briefing for riverside festival",
            "duration": "22 minutes",
            "meetingPoint": "Harbor information tent",
            "firstStop": "Vendor row",
            "firstStopOptions": ["Vendor row", "Main stage", "Children's zone", "Boat launch"],
            "studioLabel": "Zone C",
            "wifi": "HarborFest-24",
            "qaDay": "Thursday",
            "bringItem": "high-visibility vest",
            "bringOptions": ["high-visibility vest", "formal invitations", "passport copies", "chef jackets"],
            "emergencyContact": "0191 443 7720",
        },
        "section3": {
            "title": "Section 3 — Debate on Community Garden",
            "topic": "community garden expansion",
            "topicOptions": ["community garden expansion", "campus shuttle redesign", "digital library archive", "winter sports program"],
            "lead": "Mateo",
            "deadline": "5 June",
            "meeting": "every Wednesday lunchtime",
            "method": "doorstep surveys",
            "methodOptions": ["doorstep surveys", "mass emails", "automated phone calls", "satellite analysis"],
            "software": "CivicPulse",
            "budget": "£310",
            "lecturer": "Ms. Patel",
            "challenge": "securing council permits",
            "challengeOptions": ["securing council permits", "training volunteer guides", "maintaining snow machines", "booking recording studios"],
            "presentationLength": "10 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Urban Heat Islands",
            "focus": "urban heat island mitigation",
            "focusOptions": ["urban heat island mitigation", "deep sea exploration", "classical poetry translation", "culinary nutrition trends"],
            "stat": "7 degrees Celsius",
            "term": "cool roof corridors",
            "case": "Phoenix",
            "driver": "community tree planting incentives",
            "driverOptions": ["community tree planting incentives", "luxury tourism demand", "student enrolment growth", "celebrity chef endorsements"],
            "team": "Climate Resilience Unit",
            "reading": "Heatwise City Playbook",
            "pilotYear": "2020",
            "challenge": "funding long-term maintenance",
            "challengeOptions": ["funding long-term maintenance", "recruiting docents", "training divers", "securing script rights"],
            "takeaway": "layer nature-based solutions",
        },
    },
    {
        "num": "005",
        "title": "IELTS Listening Full Mock Exam 005",
        "transcript": "This set includes a theatre ticket hotline booking, a volunteer orientation briefing, a panel on digital literacy, and a lecture on coastal resilience engineering.",
        "section1": {
            "title": "Section 1 — Theatre Ticket Hotline",
            "venue": "Grand Arcade Theatre foyer",
            "venueOptions": ["Grand Arcade Theatre foyer", "Seaside Pavilion", "Hillcrest Manor", "Old Brewery Loft"],
            "date": "9th August",
            "startTime": "5:30 pm",
            "guests": "60",
            "catering": "Canapé reception",
            "cateringOptions": ["Canapé reception", "Street food court", "Formal plated dinner", "Coffee cart only"],
            "deposit": "150 pounds",
            "equipment": "lighting rig",
            "keyCollector": "Priya",
            "parking": "Weston Street car park",
            "parkingOptions": ["Weston Street car park", "Harbor level 2", "Station square", "Meadow overflow"],
            "layout": "reception stations",
        },
        "section2": {
            "title": "Section 2 — Volunteer Orientation Briefing",
            "role": "community outreach coordinator",
            "roleOptions": ["community outreach coordinator", "finance officer", "media liaison", "transport planner"],
            "topic": "neighbourhood mentoring launch",
            "duration": "20 minutes",
            "meetingPoint": "Civic Centre atrium",
            "firstStop": "Resource hub",
            "firstStopOptions": ["Resource hub", "Training studio", "Roof terrace", "Podcast booth"],
            "studioLabel": "Desk 7",
            "wifi": "MentorLink-5G",
            "qaDay": "Tuesday",
            "bringItem": "photo ID badge",
            "bringOptions": ["photo ID badge", "formal ties", "handwritten notes", "waterproof boots"],
            "emergencyContact": "0161 432 1184",
        },
        "section3": {
            "title": "Section 3 — Panel on Digital Literacy",
            "topic": "digital literacy outreach project",
            "topicOptions": ["digital literacy outreach project", "cafeteria menu redesign", "campus sculpture map", "fitness tracking study"],
            "lead": "Olivia",
            "deadline": "30 April",
            "meeting": "weekly on Thursdays",
            "method": "community workshops",
            "methodOptions": ["community workshops", "postal surveys", "lab experiments", "silent observations"],
            "software": "SkillBridge",
            "budget": "£275",
            "lecturer": "Dr. Ahmed",
            "challenge": "finding bilingual volunteers",
            "challengeOptions": ["finding bilingual volunteers", "booking the sports hall", "managing costume rentals", "storing lab chemicals"],
            "presentationLength": "14 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Coastal Resilience",
            "focus": "coastal resilience engineering",
            "focusOptions": ["coastal resilience engineering", "renaissance art history", "culinary fermentation", "space medicine"],
            "stat": "12 kilometers",
            "term": "modular breakwater units",
            "case": "Lisbon",
            "driver": "federal adaptation grants",
            "driverOptions": ["federal adaptation grants", "festival ticket sales", "alumni donations", "artisan food markets"],
            "team": "Harbor Dynamics Lab",
            "reading": "Resilient Shores Manual",
            "pilotYear": "2022",
            "challenge": "maintaining supply chains for materials",
            "challengeOptions": ["maintaining supply chains for materials", "hiring docents", "preserving manuscripts", "training sommeliers"],
            "takeaway": "engineer flexibility first",
        },
    },
    {
        "num": "006",
        "title": "IELTS Listening Full Mock Exam 006",
        "transcript": "Audio features include a healthcare workshop registration, a hospital induction briefing, a nursing research meeting, and a lecture on wearable biomedical sensors.",
        "section1": {
            "title": "Section 1 — Healthcare Workshop Registration",
            "venue": "Wellness Centre Auditorium",
            "venueOptions": ["Wellness Centre Auditorium", "Riverlight Pavilion", "Heritage Gallery", "Summit Lodge"],
            "date": "18th January",
            "startTime": "8:45 am",
            "guests": "150",
            "catering": "Plant-based lunch bowls",
            "cateringOptions": ["Plant-based lunch bowls", "Sushi platters", "High tea service", "Street taco bar"],
            "deposit": "300 pounds",
            "equipment": "live streaming kit",
            "keyCollector": "Daniel",
            "parking": "South clinic garage",
            "parkingOptions": ["South clinic garage", "Harbor deck", "Main quad bays", "Hilltop overflow"],
            "layout": "classroom pods",
        },
        "section2": {
            "title": "Section 2 — Hospital Induction Briefing",
            "role": "clinical training manager",
            "roleOptions": ["clinical training manager", "ward administrator", "pharmacy lead", "volunteer supervisor"],
            "topic": "orientation for new ward technology",
            "duration": "30 minutes",
            "meetingPoint": "Education suite lobby",
            "firstStop": "Simulation theatre",
            "firstStopOptions": ["Simulation theatre", "Pharmacy lab", "Patient lounge", "Diagnostic imaging wing"],
            "studioLabel": "Station D",
            "wifi": "WardTech-9",
            "qaDay": "Wednesday",
            "bringItem": "staff ID lanyard",
            "bringOptions": ["staff ID lanyard", "formal cufflinks", "travel documents", "sports shoes"],
            "emergencyContact": "0121 774 0058",
        },
        "section3": {
            "title": "Section 3 — Nursing Research Meeting",
            "topic": "post-operative recovery study",
            "topicOptions": ["post-operative recovery study", "campus bike audit", "student art showcase", "culinary entrepreneurship project"],
            "lead": "Felix",
            "deadline": "12 March",
            "meeting": "every Friday morning",
            "method": "patient diary analysis",
            "methodOptions": ["patient diary analysis", "random phone surveys", "library cataloguing", "stage rehearsals"],
            "software": "RecoverySync",
            "budget": "£640",
            "lecturer": "Professor Malik",
            "challenge": "ensuring consistent follow-up calls",
            "challengeOptions": ["ensuring consistent follow-up calls", "printing brochures", "booking gallery spaces", "repairing drones"],
            "presentationLength": "16 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Biomedical Sensors",
            "focus": "wearable biomedical sensors",
            "focusOptions": ["wearable biomedical sensors", "ancient maritime routes", "culinary anthropology", "modern poetry movements"],
            "stat": "millisecond precision",
            "term": "closed-loop monitoring",
            "case": "Singapore",
            "driver": "aging population needs",
            "driverOptions": ["aging population needs", "tourism marketing", "sports festival demand", "fashion cycles"],
            "team": "Vital Metrics Group",
            "reading": "Sensor Futures Whitepaper",
            "pilotYear": "2023",
            "challenge": "standardising regulatory approvals",
            "challengeOptions": ["standardising regulatory approvals", "keeping trails clean", "maintaining coral farms", "curating museum loans"],
            "takeaway": "prioritise patient trust",
        },
    },
    {
        "num": "007",
        "title": "IELTS Listening Full Mock Exam 007",
        "transcript": "Sections include a pitch venue booking, an accelerator orientation, a strategy roundtable on green logistics, and a lecture on AI supply chains.",
        "section1": {
            "title": "Section 1 — Entrepreneurship Pitch Booking",
            "venue": "Innovation Loft Auditorium",
            "venueOptions": ["Innovation Loft Auditorium", "Harbor Gallery", "Mountain View Chalet", "Library Reading Room"],
            "date": "7th March",
            "startTime": "6:15 pm",
            "guests": "110",
            "catering": "Street food tastings",
            "cateringOptions": ["Street food tastings", "Sushi omakase", "Formal banqueting", "Dessert-only buffet"],
            "deposit": "220 pounds",
            "equipment": "LED display wall",
            "keyCollector": "Hannah",
            "parking": "Innovation car park level 3",
            "parkingOptions": ["Innovation car park level 3", "City south lot", "Seafront bays", "North meadow overflow"],
            "layout": "demo booths",
        },
        "section2": {
            "title": "Section 2 — Startup Accelerator Briefing",
            "role": "program director",
            "roleOptions": ["program director", "finance mentor", "community manager", "legal advisor"],
            "topic": "orientation for accelerator cohort",
            "duration": "28 minutes",
            "meetingPoint": "Founders Hub reception",
            "firstStop": "Prototype showcase",
            "firstStopOptions": ["Prototype showcase", "Mentor lounge", "Roof deck", "Finance office"],
            "studioLabel": "Pod 8",
            "wifi": "LaunchLab-24",
            "qaDay": "Monday",
            "bringItem": "laptop and charger",
            "bringOptions": ["laptop and charger", "formal gowns", "printed resumes", "gym kit"],
            "emergencyContact": "0131 664 8022",
        },
        "section3": {
            "title": "Section 3 — Roundtable on Green Logistics",
            "topic": "green last-mile logistics pilot",
            "topicOptions": ["green last-mile logistics pilot", "campus choir programme", "digital library interface", "student wellness fair"],
            "lead": "Ibrahim",
            "deadline": "2 May",
            "meeting": "fortnightly on Tuesdays",
            "method": "sensor-enabled delivery trials",
            "methodOptions": ["sensor-enabled delivery trials", "email interviews", "focus groups only", "lab dissections"],
            "software": "RouteSense",
            "budget": "£510",
            "lecturer": "Dr. Harper",
            "challenge": "balancing courier schedules",
            "challengeOptions": ["balancing courier schedules", "finding rehearsal pianists", "managing museum humidity", "coordinating swim lanes"],
            "presentationLength": "13 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Supply Chain AI",
            "focus": "AI optimisation of supply chains",
            "focusOptions": ["AI optimisation of supply chains", "ethnomusicology fieldwork", "culinary pastry science", "ancient language revival"],
            "stat": "18 percent cost reduction",
            "term": "predictive routing engine",
            "case": "Busan",
            "driver": "real-time inventory visibility",
            "driverOptions": ["real-time inventory visibility", "festival sponsorships", "beach tourism booms", "student orientation demand"],
            "team": "LogiMind Centre",
            "reading": "Adaptive Supply Lines Journal",
            "pilotYear": "2020",
            "challenge": "data-sharing agreements between partners",
            "challengeOptions": ["data-sharing agreements between partners", "growing rare orchids", "restoring antique maps", "maintaining orchestra archives"],
            "takeaway": "treat data as shared infrastructure",
        },
    },
    {
        "num": "008",
        "title": "IELTS Listening Full Mock Exam 008",
        "transcript": "The listening paper spans a science expo registration call, a STEM roadshow briefing, a coding programme evaluation, and a lecture on quantum materials.",
        "section1": {
            "title": "Section 1 — Science Expo Registration",
            "venue": "Discovery Hall Atrium",
            "venueOptions": ["Discovery Hall Atrium", "Riverside Deck", "Grand Ballroom", "Artisan Market Barn"],
            "date": "11th February",
            "startTime": "11:00 am",
            "guests": "200",
            "catering": "Interactive tasting stations",
            "cateringOptions": ["Interactive tasting stations", "Family-style supper", "High tea tiered trays", "Pizza buffet"],
            "deposit": "280 pounds",
            "equipment": "interactive demo tables",
            "keyCollector": "Lucas",
            "parking": "Science centre west lot",
            "parkingOptions": ["Science centre west lot", "Harbor pier spaces", "Station forecourt", "Hillside lane"],
            "layout": "exhibit clusters",
        },
        "section2": {
            "title": "Section 2 — STEM Outreach Briefing",
            "role": "schools liaison officer",
            "roleOptions": ["schools liaison officer", "bus coordinator", "press officer", "museum curator"],
            "topic": "mobile science lab roadshow",
            "duration": "26 minutes",
            "meetingPoint": "Laboratory loading bay",
            "firstStop": "Robotics carriage",
            "firstStopOptions": ["Robotics carriage", "Planetarium dome", "VR theatre", "Chemistry pod"],
            "studioLabel": "Unit B",
            "wifi": "STEMvan-6",
            "qaDay": "Wednesday",
            "bringItem": "safety footwear",
            "bringOptions": ["safety footwear", "formal blazers", "paper tickets", "hiking poles"],
            "emergencyContact": "01792 430 667",
        },
        "section3": {
            "title": "Section 3 — Youth Coding Evaluation",
            "topic": "youth coding bootcamp evaluation",
            "topicOptions": ["youth coding bootcamp evaluation", "gardening society plan", "art history exhibition", "culinary pop-up event"],
            "lead": "Serena",
            "deadline": "19 July",
            "meeting": "every second Thursday",
            "method": "pre- and post-course surveys",
            "methodOptions": ["pre- and post-course surveys", "street intercept interviews", "archival dig", "product taste tests"],
            "software": "CodePulse",
            "budget": "£390",
            "lecturer": "Mr. Blake",
            "challenge": "tracking parental consent forms",
            "challengeOptions": ["tracking parental consent forms", "reserving dance studios", "shipping fragile sculptures", "maintaining kitchen equipment"],
            "presentationLength": "11 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Quantum Materials",
            "focus": "quantum materials for energy storage",
            "focusOptions": ["quantum materials for energy storage", "ancient theatre history", "culinary herbs", "sports psychology"],
            "stat": "97 percent retention rate",
            "term": "layered perovskite lattice",
            "case": "Dresden",
            "driver": "demand for grid-scale batteries",
            "driverOptions": ["demand for grid-scale batteries", "tourist festival calendars", "luxury dining trends", "student orientation fairs"],
            "team": "Quantum Horizons Lab",
            "reading": "Emerging Materials Review",
            "pilotYear": "2024",
            "challenge": "scaling crystal fabrication",
            "challengeOptions": ["scaling crystal fabrication", "booking orchestra tours", "restoring stone carvings", "managing athlete transfers"],
            "takeaway": "balance stability with efficiency",
        },
    },
    {
        "num": "009",
        "title": "IELTS Listening Full Mock Exam 009",
        "transcript": "Learners will work through a language centre placement call, a study abroad briefing, an alumni mentoring meeting, and a lecture on social impact metrics.",
        "section1": {
            "title": "Section 1 — Language Centre Placement",
            "venue": "Elm House Seminar Suite",
            "venueOptions": ["Elm House Seminar Suite", "Harborview Loft", "Old Mill Barn", "Sunset Terrace"],
            "date": "6th September",
            "startTime": "4:00 pm",
            "guests": "45",
            "catering": "Global tasting platters",
            "cateringOptions": ["Global tasting platters", "Vegan street food", "Plated degustation", "Coffee and pastries"],
            "deposit": "120 pounds",
            "equipment": "digital recording booth",
            "keyCollector": "Marco",
            "parking": "Language centre courtyard",
            "parkingOptions": ["Language centre courtyard", "Multi-storey level 1", "Riverside lay-by", "Overflow paddock"],
            "layout": "seminar pods",
        },
        "section2": {
            "title": "Section 2 — Study Abroad Briefing",
            "role": "international programmes advisor",
            "roleOptions": ["international programmes advisor", "visa consultant", "travel agent", "student ambassador"],
            "topic": "pre-departure orientation",
            "duration": "24 minutes",
            "meetingPoint": "Global Hub theatre",
            "firstStop": "Visa documentation desk",
            "firstStopOptions": ["Visa documentation desk", "Accommodation counter", "Insurance kiosk", "Language lounge"],
            "studioLabel": "Table 5",
            "wifi": "GlobalPrep-11",
            "qaDay": "Thursday",
            "bringItem": "passport photocopies",
            "bringOptions": ["passport photocopies", "formal evening wear", "sports uniforms", "studio microphones"],
            "emergencyContact": "0141 305 6672",
        },
        "section3": {
            "title": "Section 3 — Alumni Mentoring Roundtable",
            "topic": "alumni mentoring platform launch",
            "topicOptions": ["alumni mentoring platform launch", "campus bike hire expansion", "student theatre festival", "nutrition awareness week"],
            "lead": "Tara",
            "deadline": "8 January",
            "meeting": "bi-weekly on Mondays",
            "method": "matching algorithm testing",
            "methodOptions": ["matching algorithm testing", "door-to-door fundraising", "satellite imaging", "kitchen audits"],
            "software": "MentorMesh",
            "budget": "£360",
            "lecturer": "Dr. Sato",
            "challenge": "keeping mentors engaged long-term",
            "challengeOptions": ["keeping mentors engaged long-term", "scheduling the swimming pool", "cataloguing costume storage", "managing greenhouse humidity"],
            "presentationLength": "9 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Social Impact Metrics",
            "focus": "measuring social impact outcomes",
            "focusOptions": ["measuring social impact outcomes", "marine archaeology", "culinary history", "urban street art"],
            "stat": "11 core indicators",
            "term": "outcome attribution matrix",
            "case": "Cape Town",
            "driver": "donor reporting expectations",
            "driverOptions": ["donor reporting expectations", "tourist souvenir sales", "regional food trends", "student art fairs"],
            "team": "Impact Evaluation Consortium",
            "reading": "Evidence for Change Handbook",
            "pilotYear": "2018",
            "challenge": "capturing long-term follow-up data",
            "challengeOptions": ["capturing long-term follow-up data", "training diving crews", "sourcing spice blends", "restoring murals"],
            "takeaway": "link metrics to lived experience",
        },
    },
    {
        "num": "010",
        "title": "IELTS Listening Full Mock Exam 010",
        "transcript": "Audio features a corporate retreat planning call, a leadership retreat briefing, a workshop on hybrid work, and a lecture on adaptive workspaces.",
        "section1": {
            "title": "Section 1 — Corporate Retreat Planning",
            "venue": "Summit Ridge Lodge",
            "venueOptions": ["Summit Ridge Lodge", "Harbor Banquet Hall", "City Arts Loft", "Garden Terrace Marquee"],
            "date": "15th November",
            "startTime": "2:30 pm",
            "guests": "140",
            "catering": "Seasonal tasting menu",
            "cateringOptions": ["Seasonal tasting menu", "Street food courts", "Tapas evening", "Dessert showcase"],
            "deposit": "400 pounds",
            "equipment": "hybrid meeting console",
            "keyCollector": "Elena",
            "parking": "Lodge upper car park",
            "parkingOptions": ["Lodge upper car park", "Harbor deck level 4", "Station car park", "Meadow overflow field"],
            "layout": "cabaret rounds",
        },
        "section2": {
            "title": "Section 2 — Leadership Retreat Briefing",
            "role": "organisational coach",
            "roleOptions": ["organisational coach", "finance director", "travel coordinator", "wellness officer"],
            "topic": "leadership retreat agenda",
            "duration": "27 minutes",
            "meetingPoint": "Summit Pavilion lobby",
            "firstStop": "Mindfulness deck",
            "firstStopOptions": ["Mindfulness deck", "Strategy lab", "Innovation trail", "Dining hall"],
            "studioLabel": "Cabin 6",
            "wifi": "SummitPeak-12",
            "qaDay": "Sunday",
            "bringItem": "weatherproof jacket",
            "bringOptions": ["weatherproof jacket", "formal blazers", "passport wallet", "sports racket"],
            "emergencyContact": "01865 905 443",
        },
        "section3": {
            "title": "Section 3 — Hybrid Work Workshop",
            "topic": "hybrid work policy playbook",
            "topicOptions": ["hybrid work policy playbook", "student orientation concert", "heritage mural project", "nutrition app launch"],
            "lead": "Georgia",
            "deadline": "21 February",
            "meeting": "every other Wednesday",
            "method": "employee listening sessions",
            "methodOptions": ["employee listening sessions", "mail-out questionnaires", "soil sampling", "audition recordings"],
            "software": "PulseWorks",
            "budget": "£430",
            "lecturer": "Mr. Donovan",
            "challenge": "synthesising feedback from global teams",
            "challengeOptions": ["synthesising feedback from global teams", "booking the recital hall", "maintaining greenhouse lighting", "curating pop-up kitchens"],
            "presentationLength": "17 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Adaptive Workspaces",
            "focus": "adaptive workspaces and wellbeing",
            "focusOptions": ["adaptive workspaces and wellbeing", "marine conservation", "culinary spices", "ancient theatre restoration"],
            "stat": "73 percent staff satisfaction",
            "term": "dynamic zoning model",
            "case": "Melbourne",
            "driver": "employee wellbeing mandates",
            "driverOptions": ["employee wellbeing mandates", "coastal tourism spending", "artisan market buzz", "student film festivals"],
            "team": "Worklife Futures Lab",
            "reading": "Healthy Offices Blueprint",
            "pilotYear": "2022",
            "challenge": "retrofitting legacy HVAC systems",
            "challengeOptions": ["retrofitting legacy HVAC systems", "training scuba teams", "sourcing organic saffron", "preserving stage props"],
            "takeaway": "design with people at centre",
        },
    },
    {
        "num": "011",
        "title": "IELTS Listening Full Mock Exam 011",
        "transcript": "Listeners encounter an art fair coordination call, a curator walkthrough briefing, a symposium on creative economies, and a lecture on creative placemaking.",
        "section1": {
            "title": "Section 1 — Art Fair Coordination",
            "venue": "Gallery Quarter Atrium",
            "venueOptions": ["Gallery Quarter Atrium", "Harbor Promenade", "Skyline Terrace", "Old Mill Warehouse"],
            "date": "2nd April",
            "startTime": "1:00 pm",
            "guests": "85",
            "catering": "Local artisan platters",
            "cateringOptions": ["Local artisan platters", "Street vendor alley", "Formal tasting menu", "Coffeehouse service"],
            "deposit": "210 pounds",
            "equipment": "hanging lighting rails",
            "keyCollector": "Naomi",
            "parking": "Artists' loading zone",
            "parkingOptions": ["Artists' loading zone", "City garage level 5", "Riverside strip", "East meadow parking"],
            "layout": "gallery walkways",
        },
        "section2": {
            "title": "Section 2 — Curator Walkthrough Briefing",
            "role": "lead curator",
            "roleOptions": ["lead curator", "logistics director", "press liaison", "security chief"],
            "topic": "preview of the international art fair",
            "duration": "23 minutes",
            "meetingPoint": "Atrium welcome desk",
            "firstStop": "Emerging artists hall",
            "firstStopOptions": ["Emerging artists hall", "Sculpture courtyard", "Video art studio", "Collectors lounge"],
            "studioLabel": "Booth 12",
            "wifi": "ArtFair-2025",
            "qaDay": "Friday",
            "bringItem": "artist accreditation lanyard",
            "bringOptions": ["artist accreditation lanyard", "formal tuxedo", "paper invitations", "sports trainers"],
            "emergencyContact": "0203 988 5511",
        },
        "section3": {
            "title": "Section 3 — Creative Economies Symposium",
            "topic": "creative economies impact report",
            "topicOptions": ["creative economies impact report", "campus recycling drive", "student robotics league", "wellness retreat"],
            "lead": "Jules",
            "deadline": "14 September",
            "meeting": "weekly on Mondays",
            "method": "case-study interviews",
            "methodOptions": ["case-study interviews", "bulk email survey", "soil nutrient testing", "video rehearsals"],
            "software": "CultureScope",
            "budget": "£480",
            "lecturer": "Professor Lane",
            "challenge": "obtaining comparable financial data",
            "challengeOptions": ["obtaining comparable financial data", "arranging snow grooming", "booking theatre seats", "restoring antique furniture"],
            "presentationLength": "18 minutes",
        },
        "section4": {
            "title": "Section 4 — Lecture on Creative Placemaking",
            "focus": "creative placemaking for urban renewal",
            "focusOptions": ["creative placemaking for urban renewal", "marine biodiversity tracking", "molecular gastronomy", "ancient epic poetry"],
            "stat": "15-year investment horizon",
            "term": "cultural anchor sites",
            "case": "Glasgow",
            "driver": "public-private partnership funding",
            "driverOptions": ["public-private partnership funding", "seasonal tourist cruises", "culinary awards circuit", "student fashion week"],
            "team": "Civic Arts Observatory",
            "reading": "Placemakers Field Guide",
            "pilotYear": "2017",
            "challenge": "balancing community voices",
            "challengeOptions": ["balancing community voices", "monitoring coral spawn", "sourcing specialty ingredients", "translating manuscripts"],
            "takeaway": "build with residents, not for them",
        },
    },
]


def build_section(section_number: int, ctx: dict, slug: str, suffix: str) -> dict:
    audio_url = f"https://cdn.example.com/audio/listening/full-{suffix}-section{section_number}.mp3"
    if section_number == 1:
        s = ctx
        questions = [
            {
                "id": f"{slug}-s{section_number}-q1",
                "type": "mcq",
                "prompt": "Which venue is reserved for the event?",
                "options": s["venueOptions"],
                "answer": s["venue"],
            },
            {
                "id": f"{slug}-s{section_number}-q2",
                "type": "gap",
                "prompt": "Event date confirmed",
                "answer": s["date"],
            },
            {
                "id": f"{slug}-s{section_number}-q3",
                "type": "gap",
                "prompt": "Start time",
                "answer": s["startTime"],
            },
            {
                "id": f"{slug}-s{section_number}-q4",
                "type": "gap",
                "prompt": "Number of attendees",
                "answer": s["guests"],
            },
            {
                "id": f"{slug}-s{section_number}-q5",
                "type": "mcq",
                "prompt": "Catering choice",
                "options": s["cateringOptions"],
                "answer": s["catering"],
            },
            {
                "id": f"{slug}-s{section_number}-q6",
                "type": "gap",
                "prompt": "Deposit amount due",
                "answer": s["deposit"],
            },
            {
                "id": f"{slug}-s{section_number}-q7",
                "type": "gap",
                "prompt": "Special equipment requested",
                "answer": s["equipment"],
            },
            {
                "id": f"{slug}-s{section_number}-q8",
                "type": "short",
                "prompt": "Who will collect the keys?",
                "answer": s["keyCollector"],
            },
            {
                "id": f"{slug}-s{section_number}-q9",
                "type": "mcq",
                "prompt": "Where should guests park?",
                "options": s["parkingOptions"],
                "answer": s["parking"],
            },
            {
                "id": f"{slug}-s{section_number}-q10",
                "type": "gap",
                "prompt": "Preferred seating layout",
                "answer": s["layout"],
            },
        ]
        return {
            "id": f"section-{section_number}",
            "title": s["title"],
            "audioUrl": audio_url,
            "questions": questions,
        }

    if section_number == 2:
        s = ctx
        questions = [
            {
                "id": f"{slug}-s{section_number}-q1",
                "type": "mcq",
                "prompt": "What is the speaker's role?",
                "options": s["roleOptions"],
                "answer": s["role"],
            },
            {
                "id": f"{slug}-s{section_number}-q2",
                "type": "gap",
                "prompt": "Main briefing topic",
                "answer": s["topic"],
            },
            {
                "id": f"{slug}-s{section_number}-q3",
                "type": "gap",
                "prompt": "Duration of the talk",
                "answer": s["duration"],
            },
            {
                "id": f"{slug}-s{section_number}-q4",
                "type": "gap",
                "prompt": "Meeting point",
                "answer": s["meetingPoint"],
            },
            {
                "id": f"{slug}-s{section_number}-q5",
                "type": "mcq",
                "prompt": "First location on the tour",
                "options": s["firstStopOptions"],
                "answer": s["firstStop"],
            },
            {
                "id": f"{slug}-s{section_number}-q6",
                "type": "gap",
                "prompt": "Map label for the creative studio",
                "answer": s["studioLabel"],
            },
            {
                "id": f"{slug}-s{section_number}-q7",
                "type": "gap",
                "prompt": "Wi-Fi access code",
                "answer": s["wifi"],
            },
            {
                "id": f"{slug}-s{section_number}-q8",
                "type": "short",
                "prompt": "Which day includes the live Q&A?",
                "answer": s["qaDay"],
            },
            {
                "id": f"{slug}-s{section_number}-q9",
                "type": "mcq",
                "prompt": "What must participants bring?",
                "options": s["bringOptions"],
                "answer": s["bringItem"],
            },
            {
                "id": f"{slug}-s{section_number}-q10",
                "type": "gap",
                "prompt": "Emergency contact number",
                "answer": s["emergencyContact"],
            },
        ]
        return {
            "id": f"section-{section_number}",
            "title": s["title"],
            "audioUrl": audio_url,
            "questions": questions,
        }

    if section_number == 3:
        s = ctx
        questions = [
            {
                "id": f"{slug}-s{section_number}-q1",
                "type": "mcq",
                "prompt": "What project are the students discussing?",
                "options": s["topicOptions"],
                "answer": s["topic"],
            },
            {
                "id": f"{slug}-s{section_number}-q2",
                "type": "gap",
                "prompt": "Project lead",
                "answer": s["lead"],
            },
            {
                "id": f"{slug}-s{section_number}-q3",
                "type": "gap",
                "prompt": "Submission deadline",
                "answer": s["deadline"],
            },
            {
                "id": f"{slug}-s{section_number}-q4",
                "type": "gap",
                "prompt": "Team meeting cadence",
                "answer": s["meeting"],
            },
            {
                "id": f"{slug}-s{section_number}-q5",
                "type": "mcq",
                "prompt": "Chosen research method",
                "options": s["methodOptions"],
                "answer": s["method"],
            },
            {
                "id": f"{slug}-s{section_number}-q6",
                "type": "gap",
                "prompt": "Software platform",
                "answer": s["software"],
            },
            {
                "id": f"{slug}-s{section_number}-q7",
                "type": "gap",
                "prompt": "Allocated budget",
                "answer": s["budget"],
            },
            {
                "id": f"{slug}-s{section_number}-q8",
                "type": "short",
                "prompt": "Which lecturer will review their draft?",
                "answer": s["lecturer"],
            },
            {
                "id": f"{slug}-s{section_number}-q9",
                "type": "mcq",
                "prompt": "Primary challenge identified",
                "options": s["challengeOptions"],
                "answer": s["challenge"],
            },
            {
                "id": f"{slug}-s{section_number}-q10",
                "type": "gap",
                "prompt": "Planned presentation length",
                "answer": s["presentationLength"],
            },
        ]
        return {
            "id": f"section-{section_number}",
            "title": s["title"],
            "audioUrl": audio_url,
            "questions": questions,
        }

    if section_number == 4:
        s = ctx
        questions = [
            {
                "id": f"{slug}-s{section_number}-q1",
                "type": "mcq",
                "prompt": "What is the lecture mainly about?",
                "options": s["focusOptions"],
                "answer": s["focus"],
            },
            {
                "id": f"{slug}-s{section_number}-q2",
                "type": "gap",
                "prompt": "Key statistic mentioned",
                "answer": s["stat"],
            },
            {
                "id": f"{slug}-s{section_number}-q3",
                "type": "gap",
                "prompt": "Term introduced by the lecturer",
                "answer": s["term"],
            },
            {
                "id": f"{slug}-s{section_number}-q4",
                "type": "gap",
                "prompt": "City used as a case study",
                "answer": s["case"],
            },
            {
                "id": f"{slug}-s{section_number}-q5",
                "type": "mcq",
                "prompt": "Main driver behind the initiative",
                "options": s["driverOptions"],
                "answer": s["driver"],
            },
            {
                "id": f"{slug}-s{section_number}-q6",
                "type": "gap",
                "prompt": "Research team leading the work",
                "answer": s["team"],
            },
            {
                "id": f"{slug}-s{section_number}-q7",
                "type": "gap",
                "prompt": "Suggested further reading",
                "answer": s["reading"],
            },
            {
                "id": f"{slug}-s{section_number}-q8",
                "type": "short",
                "prompt": "Pilot programme launch year",
                "answer": s["pilotYear"],
            },
            {
                "id": f"{slug}-s{section_number}-q9",
                "type": "mcq",
                "prompt": "Ongoing challenge highlighted",
                "options": s["challengeOptions"],
                "answer": s["challenge"],
            },
            {
                "id": f"{slug}-s{section_number}-q10",
                "type": "gap",
                "prompt": "Final takeaway phrase",
                "answer": s["takeaway"],
            },
        ]
        return {
            "id": f"section-{section_number}",
            "title": s["title"],
            "audioUrl": audio_url,
            "questions": questions,
        }

    raise ValueError(f"Unsupported section number: {section_number}")


def build_test(entry: dict) -> dict:
    suffix = entry["num"]
    slug = f"ielts-listening-full-{suffix}"
    sections = [
        build_section(1, entry["section1"], slug, suffix),
        build_section(2, entry["section2"], slug, suffix),
        build_section(3, entry["section3"], slug, suffix),
        build_section(4, entry["section4"], slug, suffix),
    ]
    return {
        "id": slug,
        "title": entry["title"],
        "durationSec": 2400,
        "transcript": entry["transcript"],
        "sections": sections,
    }


def main() -> None:
    base = Path(__file__).resolve().parents[1] / "data" / "listening"
    base.mkdir(parents=True, exist_ok=True)
    for entry in TESTS:
        test = build_test(entry)
        target = base / f"full-exam-{entry['num']}.json"
        target.write_text(json.dumps(test, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
