create table public.mock_checkpoints (
  id bigint generated by default as identity primary key,
  attempt_id text not null,
  user_id uuid references auth.users(id) on delete cascade,
  section_idx smallint not null,
  mock_id text,
  snapshot jsonb not null,
  elapsed_sec integer default 0,
  duration_sec integer,
  completed boolean not null default false,
  created_at timestamptz not null default now()
);
