-- Create exam_events table to log anti-cheat events (idempotent + RLS)
create table if not exists public.exam_events (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null,
  user_id uuid references auth.users(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now()
);

alter table if exists public.exam_events enable row level security;

-- Users can view their own events
do $$
begin
  create policy "Users view own exam events" on public.exam_events
    for select to authenticated
    using (auth.uid() = user_id);
exception when duplicate_object then null; end$$;

-- Users insert their own events
do $$
begin
  create policy "Users insert exam events" on public.exam_events
    for insert to authenticated
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end$$;
