name: Accessibility checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run test:a11y
