name: Design System Guard
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  ds-guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (frozen)
        run: npm ci

      - name: Run DS guard
        run: npm run ds:guard
